# Generated by Django 6.1.1 on 2026-09-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('cover_image', models.ImageField(upload_to='blogs/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('headline_1', models.CharField(max_length=255)),
                ('description_1', models.TextField()),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='blogs/sections/')),
                ('headline_2', models.CharField(blank=True, max_length=255, null=True)),
                ('description_2', models.TextField(blank=True, null=True)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='blogs/sections/')),
                ('headline_3', models.CharField(blank=True, max_length=255, null=True)),
                ('description_3', models.TextField(blank=True, null=True)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='blogs/sections/')),
                ('headline_4', models.CharField(blank=True, max_length=255, null=True)),
                ('description_4', models.TextField(blank=True, null=True)),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='blogs/sections/')),
                ('headline_5', models.CharField(blank=True, max_length=255, null=True)),
                ('description_5', models.TextField(blank=True, null=True)),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='blogs/sections/')),
                ('headline_6', models.CharField(blank=True, max_length=255, null=True)),
                ('description_6', models.TextField(blank=True, null=True)),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='blogs/sections/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('hero_cover_image', models.ImageField(upload_to='profile/')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('tags', models.CharField(help_text='Comma separated tags e.g. React, Django, Tailwind', max_length=200)),
                ('live_demo_url', models.URLField(help_text='Link to Vercel, Render, Netlify, etc.')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False, help_text='Check to feature on home page (up to 3)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
